config/routes.rb
Rails.application.routes.draw do

  resources :schemes
  mount Ckeditor::Engine => '/ckeditor'
  mount Rapidfire::Engine => "/rapidfire"

 Blogo::Routes.mount_to(self, at: '/blog')
 get 'emailapi/index' => 'emailapi#index'
 post 'emailapi/subscribe' => 'emailapi#subscribe'

  post 'reviews/create'
  get 'reviews/show'
  resources :entries
  resources :categories
  resources :updates
  get 'home'=>'home#index'
  get 'coming-soon'=>'home#coming_soon'
  get 'about-us'=>'home#about_us'
  get 'search'=>'home#search'
  resources :forum_posts do
    resources :comments
  end
  match 'forum' ,to: 'forum_posts#index', via: [:get]

  get 'faq'=>'home#faq'
  get 'map-display'=>'home#map_display'
  resources :updates do
    get :autocomplete_tag_name, :on => :collection
  end

  root 'home#coming_soon'
   devise_for :users, :controllers => { :registrations => 'registrations' ,:omniauth_callbacks => "omniauth_callbacks",:sessions => 'sessions',confirmations: 'confirmations',:passwords => "passwords"}

  resources :products
  resource :shopping_cart
  post 'verify_token' =>'home#verify_token'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :entries
  has_many :schemes
  # def to_param
  #   "#{id} #{category_name}".parameterize
  # end
  validates_presence_of :category_name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum_post
end

app/models/entry.rb
require 'elasticsearch/model'
class Entry < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  # belongs_to :owner
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_many :schemes
  # delegate :owner_name,:phone_number ,:to => :owner, :prefix => true
  validates_presence_of :latitude,:longitude,:address,:other_details
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def avg_rating
    rating= self.reviews.sum(:rating)
    avg_rating=(rating/self.reviews.count) rescue nil
  end
  def as_indexed_json(options={})
    as_json(
      only: [:address, :state, :city, :country,:pincode,:other_details],
      include: {category: {only: [:category_name]}}
    )
  end

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :entry
validates_presence_of :content,:rating
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, :uniqueness => {:case_sensitive => false}
end

app/models/scheme.rb
class Scheme < ActiveRecord::Base
  belongs_to :entry
  belongs_to :category
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
    acts_as_shopping_cart_using :shopping_cart_item
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  acts_as_shopping_cart_item_for :shopping_cart
end

app/models/update.rb
class Update < ActiveRecord::Base
  extend FriendlyId
  friendly_id :topic, use: :slugged
  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, :confirmable
  has_and_belongs_to_many :roles
  validates_presence_of :email
  has_many :forum_posts
  has_many :comments
 attr_accessor :full_name

  # Getter
  def full_name
    [first_name, last_name].join(' ')
  end

  # Setter
  def full_name=(name)
    split = name.split(' ', 2)
    self.first_name = split.first
    self.last_name = split.last
  end
  def self.from_omniauth(auth)
    data = auth.info
    user = User.where(:email => data.email).first rescue nil

    unless user
      user = User.new(provider: auth.provider, uid: auth.uid, email: data.email, password: Devise.friendly_token[0,20], first_name:auth.info.name.split(" ")[0],last_name:auth.info.name.split(" ")[1])
      # user.skip_confirmation!
      # profile=user.build_profile
      user.save!(validate: false)
    end
    user
  end
   def is?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  def admin?
    self.roles.find_by_name("admin").present? ? true : false
  end
def admin
  # has_role?(:admin)
end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(update_params)
    @update.tag_list.add(params[:update][:tag_list] )
    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:topic, :details,:tag_list=>[] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emailapi_helper.rb
module EmailapiHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/schemes_helper.rb
module SchemesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= simple_form_for(@update) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :topic %>
    <%= f.input :details %>
    <%#= f.input :tag_list%>
    <%= f.input :tag_list, :label => "News Tag", :"data-delimiter" => ' ' ,:url => autocomplete_tag_name_updates_path, :as => :autocomplete%>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing Update</h1>

<%= render 'form' %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Updates</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @updates.each do |update| %>
      <tr>
        <td><%#= update.topic %></td>
        <td><%#= update.details %></td>
        <td><%#= link_to 'Show', update %></td>
        <td><%#= link_to 'Edit', edit_update_path(update) %></td>
        <td><%#= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Update', new_update_path %>
 -->
 <marquee bgcolor="#000080" scrollamount="2" direction="up" loop="true" width="100%" height='400px'> <center> 

    <% @updates.each do |update| %>
<font color="#ffffff">
 <strong> <%=update.topic%><br><%=update.details%> </strong></br></br>
  <%end%>
  <br> SCROLL UPWARDS<br>  
 </font></center></marquee>

app/views/updates/new.html.erb
<h1>New Update</h1>

<%= render 'form' %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @update.topic %>
</p>

<p>
  <strong>Details:</strong>
  <%= @update.details %>
</p>
<p>
<strong>Topic tags </strong>
<%=@update.tag_list.join(", ")
%>
</p>
<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>