config/routes.rb
Rails.application.routes.draw do

  resources :schemes
  mount Ckeditor::Engine => '/ckeditor'
  mount Rapidfire::Engine => "/rapidfire"

 Blogo::Routes.mount_to(self, at: '/blog')
 get 'emailapi/index' => 'emailapi#index'
 post 'emailapi/subscribe' => 'emailapi#subscribe'

  post 'reviews/create'
  get 'reviews/show'
  resources :entries
  resources :categories
  resources :updates
  get 'home'=>'home#index'
  get 'coming-soon'=>'home#coming_soon'
  get 'about-us'=>'home#about_us'
  get 'search'=>'home#search'
  resources :forum_posts do
    resources :comments
  end
  match 'forum' ,to: 'forum_posts#index', via: [:get]

  get 'faq'=>'home#faq'
  get 'map-display'=>'home#map_display'
  resources :updates do
    get :autocomplete_tag_name, :on => :collection
  end

  root 'home#coming_soon'
   devise_for :users, :controllers => { :registrations => 'registrations' ,:omniauth_callbacks => "omniauth_callbacks",:sessions => 'sessions',confirmations: 'confirmations',:passwords => "passwords"}

  resources :products
  resource :shopping_cart
  post 'verify_token' =>'home#verify_token'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :entries
  has_many :schemes
  # def to_param
  #   "#{id} #{category_name}".parameterize
  # end
  validates_presence_of :category_name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum_post
end

app/models/entry.rb
require 'elasticsearch/model'
class Entry < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  # belongs_to :owner
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_many :schemes
  # delegate :owner_name,:phone_number ,:to => :owner, :prefix => true
  validates_presence_of :latitude,:longitude,:address,:other_details
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def avg_rating
    rating= self.reviews.sum(:rating)
    avg_rating=(rating/self.reviews.count) rescue nil
  end
  def as_indexed_json(options={})
    as_json(
      only: [:address, :state, :city, :country,:pincode,:other_details],
      include: {category: {only: [:category_name]}}
    )
  end

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :entry
validates_presence_of :content,:rating
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, :uniqueness => {:case_sensitive => false}
end

app/models/scheme.rb
class Scheme < ActiveRecord::Base
  belongs_to :entry
  belongs_to :category
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
    acts_as_shopping_cart_using :shopping_cart_item
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  acts_as_shopping_cart_item_for :shopping_cart
end

app/models/update.rb
class Update < ActiveRecord::Base
  extend FriendlyId
  friendly_id :topic, use: :slugged
  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, :confirmable
  has_and_belongs_to_many :roles
  validates_presence_of :email
  has_many :forum_posts
  has_many :comments
 attr_accessor :full_name

  # Getter
  def full_name
    [first_name, last_name].join(' ')
  end

  # Setter
  def full_name=(name)
    split = name.split(' ', 2)
    self.first_name = split.first
    self.last_name = split.last
  end
  def self.from_omniauth(auth)
    data = auth.info
    user = User.where(:email => data.email).first rescue nil

    unless user
      user = User.new(provider: auth.provider, uid: auth.uid, email: data.email, password: Devise.friendly_token[0,20], first_name:auth.info.name.split(" ")[0],last_name:auth.info.name.split(" ")[1])
      # user.skip_confirmation!
      # profile=user.build_profile
      user.save!(validate: false)
    end
    user
  end
   def is?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  def admin?
    self.roles.find_by_name("admin").present? ? true : false
  end
def admin
  # has_role?(:admin)
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emailapi_helper.rb
module EmailapiHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/schemes_helper.rb
module SchemesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %><br>
    <%= f.text_field :category_name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", data: {disable_with: 'Please wait...'}%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render :partial=> 'form',:locals => { :category => @category } %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render :partial=>'form',:locals => { :category => @category } %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>